import type { AirflowOptions, QualityRule } from './etlDagTypes.js';

export interface EtlDagModel {
  versionId: number;
  logicalName: string;
  sqlMain: string;
  airflowOptions: AirflowOptions;
  qualityRules: QualityRule[];
}

function slugForDagId(name: string, versionId: number): string {
  const safe = name.replace(/[^a-zA-Z0-9_]+/g, '_').replace(/^_|_$/g, '') || 'task';
  return `etl_${safe}_${versionId}`;
}

export function generateDagPython(model: EtlDagModel): string {
  const dagId = slugForDagId(model.logicalName, model.versionId);
  const opts = model.airflowOptions;
  const retries = typeof opts.retries === 'number' ? opts.retries : 1;
  const retryDelayMinutes = typeof opts.retryDelayMinutes === 'number' ? opts.retryDelayMinutes : 5;
  const emailOnFailure = opts.emailOnFailure === true;
  const owner = (opts.owner && String(opts.owner).slice(0, 64)) || 'etl';

  const sqlCommentBlock = model.sqlMain
    .split('\n')
    .map(line => `# ${line.replace(/\r/g, '')}`)
    .join('\n');

  const qualityComment =
    model.qualityRules.length > 0
      ? model.qualityRules.map((r, i) => `# Quality rule ${i + 1}: ${JSON.stringify(r)}`).join('\n')
      : '# No quality rules configured';

  return `"""Airflow DAG generated by chatbot ETL workspace.
Logical name: ${model.logicalName}
Version id: ${model.versionId}
"""
# ----- Embedded SQL (reference; wire operators in deployment) -----
${sqlCommentBlock}
${qualityComment}
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.empty import EmptyOperator

default_args = {
    "owner": ${JSON.stringify(owner)},
    "depends_on_past": False,
    "email_on_failure": ${emailOnFailure ? 'True' : 'False'},
    "retries": ${retries},
    "retry_delay": timedelta(minutes=${retryDelayMinutes}),
}

with DAG(
    dag_id=${JSON.stringify(dagId)},
    default_args=default_args,
    description=${JSON.stringify(`ETL ${model.logicalName}`)},
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["etl", "generated"],
) as dag:
    start = EmptyOperator(task_id="start")
    done = EmptyOperator(task_id="done")
    start >> done
`;
}
