import { Router, Request, Response } from 'express';
import fs from 'fs';
import path from 'path';
import { pool } from '../config/postgres.js';
import { assertSingleSqlStatement, executeUserSql, trimRowsToPreview } from '../services/sqlQueryRunner.js';
import { generateDagPythonForPublish } from '../services/etlDagPythonClient.js';
import { buildAirflowOptionsForDag, normalizeRuntimeDepsForSave } from '../services/etlVersionPayload.js';
import { defaultCatalogType, syncEtlPublishToNeo4j } from '../services/etlNeo4jPublish.js';
import { defaultCatalog } from '../services/etlOutputTable.js';
import { triggerBackfillForPublishedDag } from '../services/airflowRestBackfill.js';
import { isAirflowRestConfigured, unpauseDagViaRestApi } from '../services/airflowRestUnpause.js';
import adhocRouter from './adhoc.js';
import etlAirflowRouter from './etlAirflow.js';

const router: Router = Router();

function dagsDir(): string {
  if (process.env.ETL_AIRFLOW_DAGS_DIR) {
    return process.env.ETL_AIRFLOW_DAGS_DIR;
  }
  if (process.env.AIRFLOW_HOME) {
    return path.join(process.env.AIRFLOW_HOME, 'dags');
  }
  return '';
}

function safeDagFileBase(name: string, versionId: number): string {
  const safe = name.replace(/[^a-zA-Z0-9_]+/g, '_').replace(/^_|_$/g, '') || 'task';
  return `etl_${safe}_${versionId}`;
}

/** 旧版 DAG 文件名 `etl_{name}_{versionId}.py`（发布新版本时顺带清理） */
function deleteLegacySlugDagFile(name: string, versionId: number): void {
  const dir = dagsDir();
  if (!dir) return;
  const fp = path.join(dir, `${safeDagFileBase(name, versionId)}.py`);
  try {
    fs.unlinkSync(fp);
  } catch {
    /* ignore */
  }
}

/** 当前版 DAG 文件名 `auto_generate_{etl_task_info.id}.py` */
function deleteAutoGenerateDagFile(etlTaskInfoId: number): void {
  const dir = dagsDir();
  if (!dir) return;
  const fp = path.join(dir, `auto_generate_${etlTaskInfoId}.py`);
  try {
    fs.unlinkSync(fp);
  } catch {
    /* ignore */
  }
}

function mapTaskVersion(row: Record<string, unknown>) {
  return {
    id: row.id,
    name: row.name,
    remark: row.remark,
    isPublished: row.is_published,
    sqlMain: row.sql_main,
    scheduleJson: row.schedule_json,
    alertJson: row.alert_json,
    runtimeDepsJson: row.runtime_deps_json,
    qualityRulesJson: row.quality_rules_json,
    taskOutput: {
      catalogName: (row.catalog_name as string) ?? '',
      databaseName: (row.database_name as string) ?? '',
      tableName: (row.table_name as string) ?? '',
    },
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function mapAirflowDeployment(row: Record<string, unknown>) {
  return {
    id: row.id,
    etlTaskVersionId: row.etl_task_version_id,
    airflowDagId: row.airflow_dag_id,
    logicalTaskName: row.logical_task_name,
    generator: row.generator,
    createdAt: row.created_at,
  };
}

function mapEtlFolder(row: Record<string, unknown>) {
  return {
    id: row.id,
    name: row.name,
    parent_id: row.parent_id,
    sort_order: row.sort_order,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

// --- ETL folders (library tree) ---

router.get('/folders', async (_req: Request, res: Response): Promise<void> => {
  try {
    const result = await pool.query(
      'SELECT id, name, parent_id, sort_order, created_at, updated_at FROM etl_folders ORDER BY sort_order, name'
    );
    res.json({ folders: result.rows.map(mapEtlFolder) });
  } catch (error) {
    console.error('Error listing etl folders:', error);
    res.status(500).json({ error: 'Failed to list folders' });
  }
});

router.post('/folders', async (req: Request, res: Response): Promise<void> => {
  try {
    const { name, parentId, sortOrder } = req.body || {};
    if (!name || typeof name !== 'string' || !name.trim()) {
      res.status(400).json({ error: 'name is required' });
      return;
    }
    const result = await pool.query(
      `INSERT INTO etl_folders (name, parent_id, sort_order)
       VALUES ($1, $2, $3)
       RETURNING id, name, parent_id, sort_order, created_at, updated_at`,
      [name.trim(), parentId || null, sortOrder ?? 0]
    );
    res.status(201).json({ folder: mapEtlFolder(result.rows[0]) });
  } catch (error) {
    console.error('Error creating etl folder:', error);
    res.status(500).json({ error: 'Failed to create folder' });
  }
});

router.put('/folders/:id', async (req: Request, res: Response): Promise<void> => {
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }
    const body = req.body || {};
    const { name, sortOrder } = body;
    const existing = await pool.query('SELECT id FROM etl_folders WHERE id = $1', [id]);
    if (existing.rows.length === 0) {
      res.status(404).json({ error: 'Folder not found' });
      return;
    }

    const updates: string[] = [];
    const values: unknown[] = [];
    let i = 1;
    if (typeof name === 'string') {
      updates.push(`name = $${i++}`);
      values.push(name);
    }
    if ('parentId' in body) {
      updates.push(`parent_id = $${i++}`);
      values.push(body.parentId == null ? null : body.parentId);
    }
    if (typeof sortOrder === 'number' && !Number.isNaN(sortOrder)) {
      updates.push(`sort_order = $${i++}`);
      values.push(sortOrder);
    }
    if (updates.length === 0) {
      res.status(400).json({ error: 'No updates' });
      return;
    }
    values.push(id);
    const result = await pool.query(
      `UPDATE etl_folders SET ${updates.join(', ')} WHERE id = $${i} RETURNING id, name, parent_id, sort_order, created_at, updated_at`,
      values
    );
    res.json({ folder: mapEtlFolder(result.rows[0]) });
  } catch (error) {
    console.error('Error updating etl folder:', error);
    res.status(500).json({ error: 'Failed to update folder' });
  }
});

router.delete('/folders/:id', async (req: Request, res: Response): Promise<void> => {
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }
    const result = await pool.query('DELETE FROM etl_folders WHERE id = $1 RETURNING id', [id]);
    if (result.rows.length === 0) {
      res.status(404).json({ error: 'Folder not found' });
      return;
    }
    res.json({ success: true });
  } catch (error) {
    console.error('Error deleting etl folder:', error);
    res.status(500).json({ error: 'Failed to delete folder' });
  }
});

/** 按三层元数据查询 etl_table_partition_detail（血缘表详情「产出信息」）；分区日期倒序 + 分页 */
router.get('/table-partition-details', async (req: Request, res: Response): Promise<void> => {
  try {
    const catalog = typeof req.query.catalog === 'string' ? req.query.catalog.trim() : '';
    const database = typeof req.query.database === 'string' ? req.query.database.trim() : '';
    const table = typeof req.query.table === 'string' ? req.query.table.trim() : '';
    if (!catalog || !database || !table) {
      res.status(400).json({ error: 'catalog, database, and table query parameters are required' });
      return;
    }
    const pageRaw = parseInt(String(req.query.page ?? '1'), 10);
    const pageSizeRaw = parseInt(String(req.query.pageSize ?? '20'), 10);
    const page = Math.max(1, Number.isNaN(pageRaw) ? 1 : pageRaw);
    const pageSize = Math.min(100, Math.max(1, Number.isNaN(pageSizeRaw) ? 20 : pageSizeRaw));
    const offset = (page - 1) * pageSize;

    const countResult = await pool.query(
      `SELECT COUNT(*)::int AS c FROM etl_table_partition_detail
       WHERE catalog_name = $1 AND database_name = $2 AND table_name = $3`,
      [catalog, database, table]
    );
    const total = (countResult.rows[0]?.c as number) ?? 0;

    const result = await pool.query(
      `SELECT id, catalog_name, database_name, table_name,
              primary_partition_key, secondary_partition_key, etl_task_version_id,
              partition_date, is_verified, running_status, last_success_at,
              created_at, updated_at
       FROM etl_table_partition_detail
       WHERE catalog_name = $1 AND database_name = $2 AND table_name = $3
       ORDER BY partition_date DESC NULLS LAST, primary_partition_key ASC, secondary_partition_key ASC
       LIMIT $4 OFFSET $5`,
      [catalog, database, table, pageSize, offset]
    );
    const partitionDetails = result.rows.map(row => ({
      id: row.id as number,
      catalogName: row.catalog_name as string,
      databaseName: row.database_name as string,
      tableName: row.table_name as string,
      primaryPartitionKey: row.primary_partition_key as string,
      secondaryPartitionKey: row.secondary_partition_key as string,
      etlTaskVersionId: row.etl_task_version_id as number | null,
      partitionDate: row.partition_date,
      isVerified: row.is_verified as boolean,
      runningStatus: row.running_status as string,
      lastSuccessAt: row.last_success_at,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
    }));
    res.json({ partitionDetails, total, page, pageSize });
  } catch (error) {
    console.error('Error listing table partition details:', error);
    res.status(500).json({ error: 'Failed to list partition details' });
  }
});

router.use(adhocRouter);
router.use(etlAirflowRouter);

// --- Task development ---

/**
 * 按产出表三元组解析 ETL 逻辑任务名（etl_task_info），供链路治理跳转任务开发等场景。
 * GET /api/etl/task-name-by-output-table?catalog=&database=&table=
 */
router.get('/task-name-by-output-table', async (req: Request, res: Response): Promise<void> => {
  try {
    const database = typeof req.query.database === 'string' ? req.query.database.trim() : '';
    const table = typeof req.query.table === 'string' ? req.query.table.trim() : '';
    const catalogRaw = typeof req.query.catalog === 'string' ? req.query.catalog.trim() : '';
    const dc = defaultCatalog();
    const catalogNorm = catalogRaw || dc;

    if (!database || !table) {
      res.status(400).json({ error: 'database and table query params are required' });
      return;
    }

    const result = await pool.query(
      `SELECT i.name
       FROM etl_task_info i
       WHERE COALESCE(NULLIF(TRIM(i.catalog_name), ''), $1) = $2
         AND i.database_name = $3
         AND i.table_name = $4
       LIMIT 1`,
      [dc, catalogNorm, database, table]
    );

    if (result.rows.length === 0) {
      res.status(404).json({ error: 'No ETL task registered for this output table' });
      return;
    }

    res.json({ name: result.rows[0].name as string });
  } catch (error) {
    console.error('task-name-by-output-table:', error);
    res.status(500).json({ error: 'Failed to resolve task name' });
  }
});

router.get('/tasks', async (_req: Request, res: Response): Promise<void> => {
  try {
    const result = await pool.query(
      `SELECT i.name,
              COUNT(v.id)::int AS version_count,
              MAX(v.created_at) AS updated_at,
              (SELECT v2.id FROM etl_task_versions v2 WHERE v2.etl_task_id = i.id AND v2.is_published = true LIMIT 1) AS published_version_id,
              (SELECT v3.id FROM etl_task_versions v3
                 WHERE v3.etl_task_id = i.id
                 ORDER BY v3.updated_at DESC NULLS LAST, v3.id DESC
                 LIMIT 1) AS latest_version_id,
              i.folder_id,
              COALESCE(i.folder_sort_order, 0) AS folder_sort_order
       FROM etl_task_info i
       INNER JOIN etl_task_versions v ON v.etl_task_id = i.id
       GROUP BY i.name, i.id, i.folder_id, i.folder_sort_order
       ORDER BY COALESCE(i.folder_sort_order, 0) ASC, i.name ASC`
    );
    res.json({ tasks: result.rows });
  } catch (error) {
    console.error('Error listing etl tasks:', error);
    res.status(500).json({ error: 'Failed to list tasks' });
  }
});

/** Delete logical task: all versions (deployments cascade), folder placement, and published DAG files. */
router.delete('/tasks', async (req: Request, res: Response): Promise<void> => {
  try {
    const name = typeof req.query.name === 'string' ? req.query.name.trim() : '';
    if (!name) {
      res.status(400).json({ error: 'name query is required' });
      return;
    }

    const versions = await pool.query(
      `SELECT v.id, v.is_published, i.id AS etl_task_id FROM etl_task_versions v
       JOIN etl_task_info i ON i.id = v.etl_task_id WHERE i.name = $1`,
      [name]
    );
    if (versions.rows.length === 0) {
      res.status(404).json({ error: 'Task not found' });
      return;
    }

    const taskInfoId = versions.rows[0].etl_task_id as number;
    let removeAutoGenerate = false;
    for (const row of versions.rows) {
      if (row.is_published) {
        removeAutoGenerate = true;
        deleteLegacySlugDagFile(name, row.id as number);
      }
    }
    if (removeAutoGenerate) {
      deleteAutoGenerateDagFile(taskInfoId);
    }

    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      await client.query('DELETE FROM etl_task_info WHERE name = $1', [name]);
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    res.json({ success: true });
  } catch (error) {
    console.error('Error deleting etl task:', error);
    res.status(500).json({ error: 'Failed to delete task' });
  }
});

/** PATCH body: { name, taskOutput: { catalogName, databaseName, tableName } } — 写入 etl_task_info，与版本无关 */
router.patch('/tasks/output', async (req: Request, res: Response): Promise<void> => {
  try {
    const name = typeof req.body?.name === 'string' ? req.body.name.trim() : '';
    if (!name) {
      res.status(400).json({ error: 'name is required' });
      return;
    }
    const taskOutput = req.body?.taskOutput;
    if (!taskOutput || typeof taskOutput !== 'object') {
      res.status(400).json({ error: 'taskOutput is required' });
      return;
    }
    const to = taskOutput as Record<string, unknown>;
    const cn = typeof to.catalogName === 'string' ? to.catalogName.trim() : '';
    const dn = typeof to.databaseName === 'string' ? to.databaseName.trim() : '';
    const tn = typeof to.tableName === 'string' ? to.tableName.trim() : '';

    await pool.query(`INSERT INTO etl_task_info (name) VALUES ($1) ON CONFLICT (name) DO NOTHING`, [name]);
    const result = await pool.query(
      `UPDATE etl_task_info
       SET catalog_name = NULLIF($1, ''),
           database_name = NULLIF($2, ''),
           table_name = NULLIF($3, ''),
           updated_at = CURRENT_TIMESTAMP
       WHERE name = $4
       RETURNING catalog_name, database_name, table_name`,
      [cn, dn, tn, name]
    );
    if (result.rows.length === 0) {
      res.status(404).json({ error: 'Task not found' });
      return;
    }
    const row = result.rows[0];
    res.json({
      taskOutput: {
        catalogName: (row.catalog_name as string) ?? '',
        databaseName: (row.database_name as string) ?? '',
        tableName: (row.table_name as string) ?? '',
      },
    });
  } catch (error) {
    console.error('Error patching task output:', error);
    res.status(500).json({ error: 'Failed to update task output' });
  }
});

router.patch('/tasks/placement', async (req: Request, res: Response): Promise<void> => {
  try {
    const taskName = typeof req.body?.name === 'string' ? req.body.name.trim() : '';
    if (!taskName) {
      res.status(400).json({ error: 'name is required' });
      return;
    }
    const { folderId, sortOrder } = req.body || {};
    const hasFolder = 'folderId' in (req.body || {});
    let fid: number | null | undefined;
    if (!hasFolder) {
      fid = undefined;
    } else if (folderId === null || folderId === '') {
      fid = null;
    } else if (typeof folderId === 'number' && !Number.isNaN(folderId)) {
      fid = folderId;
    } else if (typeof folderId === 'string' && folderId.trim() !== '') {
      const p = parseInt(folderId, 10);
      fid = Number.isNaN(p) ? undefined : p;
    } else {
      fid = undefined;
    }
    if (hasFolder && fid === undefined) {
      res.status(400).json({ error: 'Invalid folderId' });
      return;
    }
    if (fid != null) {
      const chk = await pool.query('SELECT id FROM etl_folders WHERE id = $1', [fid]);
      if (chk.rows.length === 0) {
        res.status(404).json({ error: 'Folder not found' });
        return;
      }
    }
    const sort =
      typeof sortOrder === 'number' && !Number.isNaN(sortOrder)
        ? sortOrder
        : typeof sortOrder === 'string' && sortOrder !== ''
          ? parseInt(sortOrder, 10)
          : null;

    const exists = await pool.query('SELECT 1 FROM etl_task_info WHERE name = $1 LIMIT 1', [taskName]);
    if (exists.rows.length === 0) {
      res.status(404).json({ error: 'Task not found' });
      return;
    }

    if (hasFolder && fid === null) {
      await pool.query(
        `UPDATE etl_task_info SET
           folder_id = NULL,
           folder_sort_order = COALESCE($2::int, folder_sort_order),
           updated_at = CURRENT_TIMESTAMP
         WHERE name = $1`,
        [taskName, sort]
      );
    } else if (hasFolder && fid != null) {
      await pool.query(
        `UPDATE etl_task_info SET
           folder_id = $1,
           folder_sort_order = COALESCE($3::int, folder_sort_order),
           updated_at = CURRENT_TIMESTAMP
         WHERE name = $2`,
        [fid, taskName, sort]
      );
    } else if (sort != null && !Number.isNaN(sort)) {
      await pool.query(
        `UPDATE etl_task_info SET
           folder_sort_order = $2,
           folder_id = COALESCE(folder_id, (SELECT id FROM etl_folders ORDER BY id LIMIT 1)),
           updated_at = CURRENT_TIMESTAMP
         WHERE name = $1`,
        [taskName, sort]
      );
    } else {
      res.status(400).json({ error: 'folderId or sortOrder required' });
      return;
    }

    res.json({ success: true });
  } catch (error) {
    console.error('Error patching etl task placement:', error);
    res.status(500).json({ error: 'Failed to update placement' });
  }
});

router.get('/tasks/versions', async (req: Request, res: Response): Promise<void> => {
  try {
    const name = req.query.name;
    if (!name || typeof name !== 'string') {
      res.status(400).json({ error: 'name query is required' });
      return;
    }
    const result = await pool.query(
      `SELECT v.id, i.name, v.remark, v.is_published, v.sql_main,
              v.schedule_json, v.alert_json, v.runtime_deps_json, v.quality_rules_json, v.created_at, v.updated_at,
              i.catalog_name, i.database_name, i.table_name
       FROM etl_task_versions v
       JOIN etl_task_info i ON i.id = v.etl_task_id
       WHERE i.name = $1 ORDER BY v.created_at DESC`,
      [name]
    );
    res.json({ versions: result.rows.map(mapTaskVersion) });
  } catch (error) {
    console.error('Error listing task versions:', error);
    res.status(500).json({ error: 'Failed to list versions' });
  }
});

router.get('/tasks/versions/:id', async (req: Request, res: Response): Promise<void> => {
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }
    const result = await pool.query(
      `SELECT v.id, i.name, v.remark, v.is_published, v.sql_main,
              v.schedule_json, v.alert_json, v.runtime_deps_json, v.quality_rules_json, v.created_at, v.updated_at,
              i.catalog_name, i.database_name, i.table_name
       FROM etl_task_versions v
       JOIN etl_task_info i ON i.id = v.etl_task_id
       WHERE v.id = $1`,
      [id]
    );
    if (result.rows.length === 0) {
      res.status(404).json({ error: 'Version not found' });
      return;
    }
    res.json({ version: mapTaskVersion(result.rows[0]) });
  } catch (error) {
    console.error('Error loading task version:', error);
    res.status(500).json({ error: 'Failed to load version' });
  }
});

router.get('/tasks/versions/:id/deployments', async (req: Request, res: Response): Promise<void> => {
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }
    const exists = await pool.query('SELECT 1 FROM etl_task_versions WHERE id = $1', [id]);
    if (exists.rows.length === 0) {
      res.status(404).json({ error: 'Version not found' });
      return;
    }
    const result = await pool.query(
      `SELECT id, etl_task_version_id, airflow_dag_id, logical_task_name, generator, created_at
       FROM etl_airflow_deployments WHERE etl_task_version_id = $1 ORDER BY created_at DESC`,
      [id]
    );
    res.json({ deployments: result.rows.map(mapAirflowDeployment) });
  } catch (error) {
    console.error('Error listing deployments:', error);
    res.status(500).json({ error: 'Failed to list deployments' });
  }
});

/** Preview Airflow DAG Python (same renderer as publish). POST body matches DagGeneratePayload fields. */
router.post('/dag/generate', (req: Request, res: Response): void => {
  try {
    const b = req.body || {};
    const etlTaskInfoId = parseInt(String(b.etlTaskInfoId ?? ''), 10);
    const versionId = parseInt(String(b.versionId ?? ''), 10);
    const logicalName = typeof b.logicalName === 'string' ? b.logicalName.trim() : '';
    if (Number.isNaN(etlTaskInfoId) || Number.isNaN(versionId) || !logicalName) {
      res.status(400).json({ error: 'etlTaskInfoId, versionId and logicalName are required' });
      return;
    }
    const sqlMain = typeof b.sqlMain === 'string' ? b.sqlMain : '';
    const qualityRules = b.qualityRules !== undefined ? b.qualityRules : { sqlQueries: [], rules: [] };
    const runtimeDepsJson = b.runtimeDepsJson ?? {};
    const baseOpts = buildAirflowOptionsForDag(b.scheduleJson ?? {}, b.alertJson ?? {});
    const airflowOptions =
      b.airflowOptions && typeof b.airflowOptions === 'object' && !Array.isArray(b.airflowOptions)
        ? { ...baseOpts, ...(b.airflowOptions as Record<string, unknown>) }
        : baseOpts;
    const out = generateDagPythonForPublish({
      etlTaskInfoId,
      versionId,
      logicalName,
      sqlMain,
      airflowOptions,
      qualityRules,
      runtimeDepsJson,
    });
    res.json({
      dagId: out.dagId,
      pythonSource: out.pythonSource,
      format: 'node_decorators_globals',
      generator: out.generator,
    });
  } catch (err) {
    console.error('dag/generate:', err);
    res.status(500).json({ error: 'DAG generation failed' });
  }
});

router.post('/tasks/versions', async (req: Request, res: Response): Promise<void> => {
  try {
    const name = typeof req.body?.name === 'string' ? req.body.name.trim() : '';
    if (!name) {
      res.status(400).json({ error: 'name is required' });
      return;
    }
    const remark = typeof req.body?.remark === 'string' ? req.body.remark : '';
    const sqlMain = typeof req.body?.sqlMain === 'string' ? req.body.sqlMain : '';
    const scheduleJson = req.body?.scheduleJson ?? {};
    const alertJson = req.body?.alertJson ?? {};
    const runtimeDepsJson = req.body?.runtimeDepsJson ?? {};
    const qualityRulesJson = req.body?.qualityRulesJson ?? { sqlQueries: [], rules: [] };
    const runtimeDeps = normalizeRuntimeDepsForSave(runtimeDepsJson);
    const body = req.body || {};
    const hasFolderKey = 'folderId' in body;
    const rawFolderId = body.folderId;
    let placementFolderId: number | null | undefined;
    if (hasFolderKey) {
      if (rawFolderId === null || rawFolderId === '') {
        placementFolderId = null;
      } else if (typeof rawFolderId === 'number' && !Number.isNaN(rawFolderId)) {
        placementFolderId = rawFolderId;
      } else if (typeof rawFolderId === 'string') {
        const p = parseInt(rawFolderId, 10);
        placementFolderId = Number.isNaN(p) ? undefined : p;
      } else {
        placementFolderId = undefined;
      }
    }
    if (hasFolderKey && rawFolderId != null && rawFolderId !== '' && placementFolderId === undefined) {
      res.status(400).json({ error: 'Invalid folderId' });
      return;
    }
    if (placementFolderId !== null && placementFolderId !== undefined) {
      const chk = await pool.query('SELECT id FROM etl_folders WHERE id = $1', [placementFolderId]);
      if (chk.rows.length === 0) {
        res.status(404).json({ error: 'Folder not found' });
        return;
      }
    }

    await pool.query(`INSERT INTO etl_task_info (name) VALUES ($1) ON CONFLICT (name) DO NOTHING`, [name]);
    const insVer = await pool.query(
      `INSERT INTO etl_task_versions (
         etl_task_id, remark, sql_main,
         schedule_json, alert_json, runtime_deps_json, quality_rules_json
       )
       SELECT i.id, $2, $3, $4::jsonb, $5::jsonb, $6::jsonb, $7::jsonb
       FROM etl_task_info i WHERE i.name = $1
       RETURNING id`,
      [
        name,
        remark,
        sqlMain,
        JSON.stringify(scheduleJson),
        JSON.stringify(alertJson),
        JSON.stringify(runtimeDeps),
        JSON.stringify(qualityRulesJson),
      ]
    );
    const newVersionId = insVer.rows[0].id as number;

    const result = await pool.query(
      `SELECT v.id, i.name, v.remark, v.is_published, v.sql_main,
              v.schedule_json, v.alert_json, v.runtime_deps_json, v.quality_rules_json, v.created_at, v.updated_at,
              i.catalog_name, i.database_name, i.table_name
       FROM etl_task_versions v JOIN etl_task_info i ON i.id = v.etl_task_id WHERE v.id = $1`,
      [newVersionId]
    );

    if (hasFolderKey) {
      const fid = placementFolderId === undefined ? null : placementFolderId;
      await pool.query(
        `UPDATE etl_task_info SET folder_id = $1, folder_sort_order = 0, updated_at = CURRENT_TIMESTAMP WHERE name = $2`,
        [fid, name]
      );
    } else {
      await pool.query(
        `UPDATE etl_task_info SET
           folder_id = COALESCE(folder_id, (SELECT id FROM etl_folders ORDER BY id LIMIT 1)),
           updated_at = CURRENT_TIMESTAMP
         WHERE name = $1 AND folder_id IS NULL`,
        [name]
      );
    }

    res.status(201).json({ version: mapTaskVersion(result.rows[0]) });
  } catch (error) {
    console.error('Error saving task version:', error);
    res.status(500).json({ error: 'Failed to save version' });
  }
});

router.put('/tasks/versions/:id/publish', async (req: Request, res: Response): Promise<void> => {
  const client = await pool.connect();
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }

    await client.query('BEGIN');
    const versionResult = await client.query(
      `SELECT v.id, v.runtime_deps_json, v.sql_main, v.schedule_json, v.alert_json, v.quality_rules_json,
              i.id AS etl_task_id, i.name,
              i.catalog_name, i.database_name, i.table_name
       FROM etl_task_versions v
       JOIN etl_task_info i ON i.id = v.etl_task_id
       WHERE v.id = $1`,
      [id]
    );
    if (versionResult.rows.length === 0) {
      await client.query('ROLLBACK');
      res.status(404).json({ error: 'Version not found' });
      return;
    }
    const row = versionResult.rows[0];
    const logicalName = row.name as string;
    const oldPublished = await client.query(
      `SELECT v.id FROM etl_task_versions v
       JOIN etl_task_info i ON i.id = v.etl_task_id
       WHERE i.name = $1 AND v.is_published = true`,
      [logicalName]
    );

    await client.query(
      `UPDATE etl_task_versions v SET is_published = false
       FROM etl_task_info i
       WHERE v.etl_task_id = i.id AND i.name = $1 AND v.is_published = true`,
      [logicalName]
    );
    await client.query(`UPDATE etl_task_versions SET is_published = true WHERE id = $1`, [id]);
    const publishedRow = await client.query(
      `SELECT v.id, i.name, v.remark, v.is_published, v.sql_main,
              v.schedule_json, v.alert_json, v.runtime_deps_json, v.quality_rules_json, v.created_at, v.updated_at,
              i.catalog_name, i.database_name, i.table_name
       FROM etl_task_versions v JOIN etl_task_info i ON i.id = v.etl_task_id WHERE v.id = $1`,
      [id]
    );

    const airflowOptions = buildAirflowOptionsForDag(row.schedule_json, row.alert_json);

    let dagResult: { dagId: string; pythonSource: string; generator: string };
    try {
      const qualityRules = row.quality_rules_json ?? { sqlQueries: [], rules: [] };
      dagResult = generateDagPythonForPublish({
        etlTaskInfoId: row.etl_task_id as number,
        versionId: id,
        logicalName,
        sqlMain: (row.sql_main as string) || '',
        airflowOptions,
        qualityRules,
        runtimeDepsJson: row.runtime_deps_json,
      });
    } catch (dagErr) {
      await client.query('ROLLBACK');
      console.error('ETL publish: DAG generation failed:', dagErr);
      res.status(500).json({ error: 'DAG generation failed' });
      return;
    }

    for (const pr of oldPublished.rows) {
      deleteLegacySlugDagFile(logicalName, pr.id as number);
    }
    const dagDir = dagsDir();
    if (dagDir) {
      try {
        fs.mkdirSync(dagDir, { recursive: true });
        fs.writeFileSync(path.join(dagDir, `${dagResult.dagId}.py`), dagResult.pythonSource, 'utf8');
      } catch (werr) {
        await client.query('ROLLBACK');
        console.error('ETL publish: write Airflow DAG file failed:', werr);
        res.status(500).json({ error: 'Failed to write Airflow DAG file' });
        return;
      }
    } else {
      console.warn(
        'ETL publish: ETL_AIRFLOW_DAGS_DIR / AIRFLOW_HOME not set; DAG source generated but not written to disk'
      );
    }

    // 同一逻辑任务仅保留一条 deployment；清理上一发布版本遗留记录后再写入当前版本
    await client.query(`DELETE FROM etl_airflow_deployments WHERE logical_task_name = $1`, [logicalName]);

    await client.query(
      `INSERT INTO etl_airflow_deployments (etl_task_version_id, airflow_dag_id, logical_task_name, generator)
       VALUES ($1, $2, $3, $4)`,
      [id, dagResult.dagId, logicalName, dagResult.generator]
    );

    try {
      await syncEtlPublishToNeo4j({
        etlTaskId: row.etl_task_id as number,
        airflowDagId: dagResult.dagId,
        catalogType: defaultCatalogType(),
        runtimeDepsJson: row.runtime_deps_json,
        etlTaskInfo: {
          catalog_name: row.catalog_name as string | null,
          database_name: row.database_name as string | null,
          table_name: row.table_name as string | null,
        },
      });
    } catch (neoErr) {
      await client.query('ROLLBACK');
      console.error('ETL publish: Neo4j sync failed:', neoErr);
      res.status(500).json({ error: 'Neo4j lineage sync failed' });
      return;
    }

    let airflowUnpause: { skipped: true } | { ok: true } | { ok: false; error: string } = { skipped: true };
    if (isAirflowRestConfigured()) {
      const up = await unpauseDagViaRestApi(dagResult.dagId);
      if (!up.ok) {
        await client.query('ROLLBACK');
        console.error('ETL publish: Airflow REST unpause failed:', up.error);
        res.status(502).json({ error: `Airflow 启用调度失败: ${up.error}` });
        return;
      }
      airflowUnpause = { ok: true };
    }

    const airflowBackfill = await triggerBackfillForPublishedDag({
      dagId: dagResult.dagId,
      scheduleStartDateIso: airflowOptions.scheduleStartDate || '',
      cronExpression: airflowOptions.cronExpression || '',
    });
    if ('ok' in airflowBackfill && airflowBackfill.ok === false) {
      console.error('ETL publish: Airflow backfill failed:', airflowBackfill.error);
    }

    await client.query('COMMIT');
    res.json({ version: mapTaskVersion(publishedRow.rows[0]), airflowUnpause, airflowBackfill });
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error publishing task version:', error);
    res.status(500).json({ error: 'Failed to publish' });
  } finally {
    client.release();
  }
});

router.post('/tasks/dry-run', async (req: Request, res: Response): Promise<void> => {
  try {
    const sql = typeof req.body?.sql === 'string' ? req.body.sql : '';
    if (!sql.trim()) {
      res.status(400).json({ error: 'sql is required' });
      return;
    }
    try {
      assertSingleSqlStatement(sql);
    } catch (ve: unknown) {
      const msg = ve instanceof Error ? ve.message : 'Invalid SQL';
      res.status(400).json({ error: msg });
      return;
    }
    const t0 = Date.now();
    const run = await executeUserSql(sql);
    res.json({
      durationMs: Date.now() - t0,
      columns: run.columns,
      rows: trimRowsToPreview(run.rows),
      rowCount: run.rowCount,
    });
  } catch (error) {
    console.error('Error dry-run (ad-hoc body):', error);
    res.status(500).json({ error: 'Dry-run failed' });
  }
});

router.post('/tasks/versions/:id/dry-run', async (req: Request, res: Response): Promise<void> => {
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }
    const version = await pool.query('SELECT sql_main FROM etl_task_versions WHERE id = $1', [id]);
    if (version.rows.length === 0) {
      res.status(404).json({ error: 'Version not found' });
      return;
    }
    const override = typeof req.body?.sql === 'string' ? req.body.sql : null;
    const sql = (override ?? version.rows[0].sql_main) as string;
    try {
      assertSingleSqlStatement(sql);
    } catch (ve: unknown) {
      const msg = ve instanceof Error ? ve.message : 'Invalid SQL';
      res.status(400).json({ error: msg });
      return;
    }
    const t0 = Date.now();
    const run = await executeUserSql(sql);
    res.json({
      durationMs: Date.now() - t0,
      columns: run.columns,
      rows: trimRowsToPreview(run.rows),
      rowCount: run.rowCount,
    });
  } catch (error) {
    console.error('Error dry-run:', error);
    res.status(500).json({ error: 'Dry-run failed' });
  }
});

router.delete('/tasks/versions/:id', async (req: Request, res: Response): Promise<void> => {
  try {
    const id = parseInt(String(req.params.id), 10);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: 'Invalid id' });
      return;
    }
    const check = await pool.query(
      `SELECT i.name, v.is_published, i.id AS etl_task_id FROM etl_task_versions v
       JOIN etl_task_info i ON i.id = v.etl_task_id WHERE v.id = $1`,
      [id]
    );
    if (check.rows.length === 0) {
      res.status(404).json({ error: 'Version not found' });
      return;
    }

    const refCounts = await pool.query(
      `SELECT
         (SELECT COUNT(*)::int FROM etl_table_partition_detail WHERE etl_task_version_id = $1) AS n_partition,
         (SELECT COUNT(*)::int FROM etl_task_run_instances WHERE etl_task_version_id = $1) AS n_run`,
      [id]
    );
    const nPartition = refCounts.rows[0]?.n_partition as number;
    const nRun = refCounts.rows[0]?.n_run as number;
    if ((nPartition ?? 0) > 0 || (nRun ?? 0) > 0) {
      const parts: string[] = [];
      if ((nPartition ?? 0) > 0) {
        parts.push(`产出分区登记（etl_table_partition_detail）${nPartition} 条`);
      }
      if ((nRun ?? 0) > 0) {
        parts.push(`运行实例（etl_task_run_instances）${nRun} 条`);
      }
      res.status(409).json({
        error: `该版本仍被引用，无法删除：${parts.join('；')}。`,
        refs: { partitionDetails: nPartition ?? 0, runInstances: nRun ?? 0 },
      });
      return;
    }

    if (check.rows[0].is_published) {
      const name = check.rows[0].name as string;
      deleteLegacySlugDagFile(name, id);
      deleteAutoGenerateDagFile(check.rows[0].etl_task_id as number);
    }
    await pool.query('DELETE FROM etl_task_versions WHERE id = $1', [id]);
    res.json({ success: true });
  } catch (error) {
    console.error('Error deleting task version:', error);
    res.status(500).json({ error: 'Failed to delete' });
  }
});

export default router;
